package net.a11v1r15.kamenridercraftsoundevents;

import java.util.function.Supplier;

import org.slf4j.Logger;

import com.mojang.logging.LogUtils;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.ModContainer;
import net.neoforged.neoforge.registries.DeferredRegister;

// The value here should match an entry in the META-INF/neoforge.mods.toml file
@Mod(KamenRiderCraftSoundEvents.MODID)
public class KamenRiderCraftSoundEvents {
	// Define mod id in a common place for everything to reference
	public static final String MODID = "kamenridercraftsoundevents";
	// Directly reference a slf4j logger
	public static final Logger LOGGER = LogUtils.getLogger();

	public static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, KamenRiderCraftSoundEvents.MODID);

	public static final Supplier<SoundEvent> HENCHMAN_STEP = registerSoundEvent("entity.kamenridercraft.henchman.step");

	public static final Supplier<SoundEvent> HENCHMAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.henchman.ambient");
	public static final Supplier<SoundEvent> HENCHMAN_HURT = registerSoundEvent("entity.kamenridercraft.henchman.hurt");
	public static final Supplier<SoundEvent> HENCHMAN_DEATH = registerSoundEvent("entity.kamenridercraft.henchman.death");
	public static final Supplier<SoundEvent> HENCHMAN_SHOOT = registerSoundEvent("entity.kamenridercraft.henchman.shoot");

	public static final Supplier<SoundEvent> ABADDON_AMBIENT = registerSoundEvent("entity.kamenridercraft.abaddon.ambient");
	public static final Supplier<SoundEvent> ABADDON_HURT = registerSoundEvent("entity.kamenridercraft.abaddon.hurt");
	public static final Supplier<SoundEvent> ABADDON_DEATH = registerSoundEvent("entity.kamenridercraft.abaddon.death");
	public static final Supplier<SoundEvent> ABADDON_SHOOT = registerSoundEvent("entity.kamenridercraft.abaddon.shoot");
	public static final Supplier<SoundEvent> AGENT_AMBIENT = registerSoundEvent("entity.kamenridercraft.agent.ambient");
	public static final Supplier<SoundEvent> AGENT_HURT = registerSoundEvent("entity.kamenridercraft.agent.hurt");
	public static final Supplier<SoundEvent> AGENT_DEATH = registerSoundEvent("entity.kamenridercraft.agent.death");
	public static final Supplier<SoundEvent> AGENT_SHOOT = registerSoundEvent("entity.kamenridercraft.agent.shoot");
	public static final Supplier<SoundEvent> ANGUIS_MASCULUS_AMBIENT = registerSoundEvent("entity.kamenridercraft.anguis_masculus.ambient");
	public static final Supplier<SoundEvent> ANGUIS_MASCULUS_HURT = registerSoundEvent("entity.kamenridercraft.anguis_masculus.hurt");
	public static final Supplier<SoundEvent> ANGUIS_MASCULUS_DEATH = registerSoundEvent("entity.kamenridercraft.anguis_masculus.death");
	public static final Supplier<SoundEvent> ANGUIS_MASCULUS_SHOOT = registerSoundEvent("entity.kamenridercraft.anguis_masculus.shoot");
	public static final Supplier<SoundEvent> ARI_COMMANDO_AMBIENT = registerSoundEvent("entity.kamenridercraft.ari_commando.ambient");
	public static final Supplier<SoundEvent> ARI_COMMANDO_HURT = registerSoundEvent("entity.kamenridercraft.ari_commando.hurt");
	public static final Supplier<SoundEvent> ARI_COMMANDO_DEATH = registerSoundEvent("entity.kamenridercraft.ari_commando.death");
	public static final Supplier<SoundEvent> ARI_COMMANDO_SHOOT = registerSoundEvent("entity.kamenridercraft.ari_commando.shoot");
	public static final Supplier<SoundEvent> BAKENEKO_AMBIENT = registerSoundEvent("entity.kamenridercraft.bakeneko.ambient");
	public static final Supplier<SoundEvent> BAKENEKO_HURT = registerSoundEvent("entity.kamenridercraft.bakeneko.hurt");
	public static final Supplier<SoundEvent> BAKENEKO_DEATH = registerSoundEvent("entity.kamenridercraft.bakeneko.death");
	public static final Supplier<SoundEvent> BAKENEKO_SHOOT = registerSoundEvent("entity.kamenridercraft.bakeneko.shoot");
	public static final Supplier<SoundEvent> BATTA_AUGMENT_AMBIENT = registerSoundEvent("entity.kamenridercraft.batta_augment.ambient");
	public static final Supplier<SoundEvent> BATTA_AUGMENT_HURT = registerSoundEvent("entity.kamenridercraft.batta_augment.hurt");
	public static final Supplier<SoundEvent> BATTA_AUGMENT_DEATH = registerSoundEvent("entity.kamenridercraft.batta_augment.death");
	public static final Supplier<SoundEvent> BATTA_AUGMENT_SHOOT = registerSoundEvent("entity.kamenridercraft.batta_augment.shoot");
	public static final Supplier<SoundEvent> BATTLE_RAIDER_AMBIENT = registerSoundEvent("entity.kamenridercraft.battle_raider.ambient");
	public static final Supplier<SoundEvent> BATTLE_RAIDER_HURT = registerSoundEvent("entity.kamenridercraft.battle_raider.hurt");
	public static final Supplier<SoundEvent> BATTLE_RAIDER_DEATH = registerSoundEvent("entity.kamenridercraft.battle_raider.death");
	public static final Supplier<SoundEvent> BATTLE_RAIDER_SHOOT = registerSoundEvent("entity.kamenridercraft.battle_raider.shoot");
	public static final Supplier<SoundEvent> BLACK_SATAN_SOLDIER_AMBIENT = registerSoundEvent("entity.kamenridercraft.black_satan_soldier.ambient");
	public static final Supplier<SoundEvent> BLACK_SATAN_SOLDIER_HURT = registerSoundEvent("entity.kamenridercraft.black_satan_soldier.hurt");
	public static final Supplier<SoundEvent> BLACK_SATAN_SOLDIER_DEATH = registerSoundEvent("entity.kamenridercraft.black_satan_soldier.death");
	public static final Supplier<SoundEvent> BLACK_SATAN_SOLDIER_SHOOT = registerSoundEvent("entity.kamenridercraft.black_satan_soldier.shoot");
	public static final Supplier<SoundEvent> BUGSTERVIRUS_AMBIENT = registerSoundEvent("entity.kamenridercraft.bugstervirus_mob.ambient");
	public static final Supplier<SoundEvent> BUGSTERVIRUS_HURT = registerSoundEvent("entity.kamenridercraft.bugstervirus_mob.hurt");
	public static final Supplier<SoundEvent> BUGSTERVIRUS_DEATH = registerSoundEvent("entity.kamenridercraft.bugstervirus_mob.death");
	public static final Supplier<SoundEvent> BUGSTERVIRUS_SHOOT = registerSoundEvent("entity.kamenridercraft.bugstervirus_mob.shoot");
	public static final Supplier<SoundEvent> CHAP_AMBIENT = registerSoundEvent("entity.kamenridercraft.chap.ambient");
	public static final Supplier<SoundEvent> CHAP_HURT = registerSoundEvent("entity.kamenridercraft.chap.hurt");
	public static final Supplier<SoundEvent> CHAP_DEATH = registerSoundEvent("entity.kamenridercraft.chap.death");
	public static final Supplier<SoundEvent> CHAP_SHOOT = registerSoundEvent("entity.kamenridercraft.chap.shoot");
	public static final Supplier<SoundEvent> CHAP_GREY_AMBIENT = registerSoundEvent("entity.kamenridercraft.chap_grey.ambient");
	public static final Supplier<SoundEvent> CHAP_GREY_HURT = registerSoundEvent("entity.kamenridercraft.chap_grey.hurt");
	public static final Supplier<SoundEvent> CHAP_GREY_DEATH = registerSoundEvent("entity.kamenridercraft.chap_grey.death");
	public static final Supplier<SoundEvent> CHAP_GREY_SHOOT = registerSoundEvent("entity.kamenridercraft.chap_grey.shoot");
	public static final Supplier<SoundEvent> CHARYBDIS_AMBIENT = registerSoundEvent("entity.kamenridercraft.charybdis.ambient");
	public static final Supplier<SoundEvent> CHARYBDIS_HURT = registerSoundEvent("entity.kamenridercraft.charybdis.hurt");
	public static final Supplier<SoundEvent> CHARYBDIS_DEATH = registerSoundEvent("entity.kamenridercraft.charybdis.death");
	public static final Supplier<SoundEvent> CHARYBDIS_SHOOT = registerSoundEvent("entity.kamenridercraft.charybdis.shoot");
	public static final Supplier<SoundEvent> COMBAT_ROID_AMBIENT = registerSoundEvent("entity.kamenridercraft.combat_roid.ambient");
	public static final Supplier<SoundEvent> COMBAT_ROID_HURT = registerSoundEvent("entity.kamenridercraft.combat_roid.hurt");
	public static final Supplier<SoundEvent> COMBAT_ROID_DEATH = registerSoundEvent("entity.kamenridercraft.combat_roid.death");
	public static final Supplier<SoundEvent> COMBAT_ROID_SHOOT = registerSoundEvent("entity.kamenridercraft.combat_roid.shoot");
	public static final Supplier<SoundEvent> DARK_NECROM_AMBIENT = registerSoundEvent("entity.kamenridercraft.dark_necrom.ambient");
	public static final Supplier<SoundEvent> DARK_NECROM_HURT = registerSoundEvent("entity.kamenridercraft.dark_necrom.hurt");
	public static final Supplier<SoundEvent> DARK_NECROM_DEATH = registerSoundEvent("entity.kamenridercraft.dark_necrom.death");
	public static final Supplier<SoundEvent> DARK_NECROM_SHOOT = registerSoundEvent("entity.kamenridercraft.dark_necrom.shoot");
	public static final Supplier<SoundEvent> DESTRON_COMBATMAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.destron_combatman.ambient");
	public static final Supplier<SoundEvent> DESTRON_COMBATMAN_HURT = registerSoundEvent("entity.kamenridercraft.destron_combatman.hurt");
	public static final Supplier<SoundEvent> DESTRON_COMBATMAN_DEATH = registerSoundEvent("entity.kamenridercraft.destron_combatman.death");
	public static final Supplier<SoundEvent> DESTRON_COMBATMAN_SHOOT = registerSoundEvent("entity.kamenridercraft.destron_combatman.shoot");
	public static final Supplier<SoundEvent> DODO_MAGIA_CHICK_AMBIENT = registerSoundEvent("entity.kamenridercraft.dodo_magia_chick.ambient");
	public static final Supplier<SoundEvent> DODO_MAGIA_CHICK_HURT = registerSoundEvent("entity.kamenridercraft.dodo_magia_chick.hurt");
	public static final Supplier<SoundEvent> DODO_MAGIA_CHICK_DEATH = registerSoundEvent("entity.kamenridercraft.dodo_magia_chick.death");
	public static final Supplier<SoundEvent> DODO_MAGIA_CHICK_SHOOT = registerSoundEvent("entity.kamenridercraft.dodo_magia_chick.shoot");
	public static final Supplier<SoundEvent> DOGMA_FIGHTER_AMBIENT = registerSoundEvent("entity.kamenridercraft.dogma_fighter.ambient");
	public static final Supplier<SoundEvent> DOGMA_FIGHTER_HURT = registerSoundEvent("entity.kamenridercraft.dogma_fighter.hurt");
	public static final Supplier<SoundEvent> DOGMA_FIGHTER_DEATH = registerSoundEvent("entity.kamenridercraft.dogma_fighter.death");
	public static final Supplier<SoundEvent> DOGMA_FIGHTER_SHOOT = registerSoundEvent("entity.kamenridercraft.dogma_fighter.shoot");
	public static final Supplier<SoundEvent> DOWNFALL_GUARDIAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.downfall_guardian.ambient");
	public static final Supplier<SoundEvent> DOWNFALL_GUARDIAN_HURT = registerSoundEvent("entity.kamenridercraft.downfall_guardian.hurt");
	public static final Supplier<SoundEvent> DOWNFALL_GUARDIAN_DEATH = registerSoundEvent("entity.kamenridercraft.downfall_guardian.death");
	public static final Supplier<SoundEvent> DOWNFALL_GUARDIAN_SHOOT = registerSoundEvent("entity.kamenridercraft.downfall_guardian.shoot");
	public static final Supplier<SoundEvent> DREATROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.dreatrooper.ambient");
	public static final Supplier<SoundEvent> DREATROOPER_HURT = registerSoundEvent("entity.kamenridercraft.dreatrooper.hurt");
	public static final Supplier<SoundEvent> DREATROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.dreatrooper.death");
	public static final Supplier<SoundEvent> DREATROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.dreatrooper.shoot");
	public static final Supplier<SoundEvent> ELEMENTARY_INVES_RED_AMBIENT = registerSoundEvent("entity.kamenridercraft.elementary_inves_red.ambient");
	public static final Supplier<SoundEvent> ELEMENTARY_INVES_RED_HURT = registerSoundEvent("entity.kamenridercraft.elementary_inves_red.hurt");
	public static final Supplier<SoundEvent> ELEMENTARY_INVES_RED_DEATH = registerSoundEvent("entity.kamenridercraft.elementary_inves_red.death");
	public static final Supplier<SoundEvent> ELEMENTARY_INVES_RED_SHOOT = registerSoundEvent("entity.kamenridercraft.elementary_inves_red.shoot");
	public static final Supplier<SoundEvent> END_RIDER_AMBIENT = registerSoundEvent("entity.kamenridercraft.end_rider.ambient");
	public static final Supplier<SoundEvent> END_RIDER_HURT = registerSoundEvent("entity.kamenridercraft.end_rider.hurt");
	public static final Supplier<SoundEvent> END_RIDER_DEATH = registerSoundEvent("entity.kamenridercraft.end_rider.death");
	public static final Supplier<SoundEvent> END_RIDER_SHOOT = registerSoundEvent("entity.kamenridercraft.end_rider.shoot");
	public static final Supplier<SoundEvent> ENEMY_SUMMON_AMBIENT = registerSoundEvent("entity.kamenridercraft.enemy_summon.ambient");
	public static final Supplier<SoundEvent> ENEMY_SUMMON_HURT = registerSoundEvent("entity.kamenridercraft.enemy_summon.hurt");
	public static final Supplier<SoundEvent> ENEMY_SUMMON_DEATH = registerSoundEvent("entity.kamenridercraft.enemy_summon.death");
	public static final Supplier<SoundEvent> ENEMY_SUMMON_SHOOT = registerSoundEvent("entity.kamenridercraft.enemy_summon.shoot");
	public static final Supplier<SoundEvent> FOUNDATION_X_MASQUERADE_AMBIENT = registerSoundEvent("entity.kamenridercraft.foundation_x_masquerade.ambient");
	public static final Supplier<SoundEvent> FOUNDATION_X_MASQUERADE_HURT = registerSoundEvent("entity.kamenridercraft.foundation_x_masquerade.hurt");
	public static final Supplier<SoundEvent> FOUNDATION_X_MASQUERADE_DEATH = registerSoundEvent("entity.kamenridercraft.foundation_x_masquerade.death");
	public static final Supplier<SoundEvent> FOUNDATION_X_MASQUERADE_SHOOT = registerSoundEvent("entity.kamenridercraft.foundation_x_masquerade.shoot");
	public static final Supplier<SoundEvent> GAMMA_COMMANDO_AMBIENT = registerSoundEvent("entity.kamenridercraft.gamma_commandos.ambient");
	public static final Supplier<SoundEvent> GAMMA_COMMANDO_HURT = registerSoundEvent("entity.kamenridercraft.gamma_commandos.hurt");
	public static final Supplier<SoundEvent> GAMMA_COMMANDO_DEATH = registerSoundEvent("entity.kamenridercraft.gamma_commandos.death");
	public static final Supplier<SoundEvent> GAMMA_COMMANDO_SHOOT = registerSoundEvent("entity.kamenridercraft.gamma_commandos.shoot");
	public static final Supplier<SoundEvent> GHOULS_AMBIENT = registerSoundEvent("entity.kamenridercraft.ghouls.ambient");
	public static final Supplier<SoundEvent> GHOULS_HURT = registerSoundEvent("entity.kamenridercraft.ghouls.hurt");
	public static final Supplier<SoundEvent> GHOULS_DEATH = registerSoundEvent("entity.kamenridercraft.ghouls.death");
	public static final Supplier<SoundEvent> GHOULS_SHOOT = registerSoundEvent("entity.kamenridercraft.ghouls.shoot");
	public static final Supplier<SoundEvent> GIFF_JUNIOR_AMBIENT = registerSoundEvent("entity.kamenridercraft.giff_junior.ambient");
	public static final Supplier<SoundEvent> GIFF_JUNIOR_HURT = registerSoundEvent("entity.kamenridercraft.giff_junior.hurt");
	public static final Supplier<SoundEvent> GIFF_JUNIOR_DEATH = registerSoundEvent("entity.kamenridercraft.giff_junior.death");
	public static final Supplier<SoundEvent> GIFF_JUNIOR_SHOOT = registerSoundEvent("entity.kamenridercraft.giff_junior.shoot");
	public static final Supplier<SoundEvent> GM_RIDER_AMBIENT = registerSoundEvent("entity.kamenridercraft.gmrider.ambient");
	public static final Supplier<SoundEvent> GM_RIDER_HURT = registerSoundEvent("entity.kamenridercraft.gmrider.hurt");
	public static final Supplier<SoundEvent> GM_RIDER_DEATH = registerSoundEvent("entity.kamenridercraft.gmrider.death");
	public static final Supplier<SoundEvent> GM_RIDER_SHOOT = registerSoundEvent("entity.kamenridercraft.gmrider.shoot");
	public static final Supplier<SoundEvent> GOD_WARFARE_AGENT_AMBIENT = registerSoundEvent("entity.kamenridercraft.god_warfare_agent.ambient");
	public static final Supplier<SoundEvent> GOD_WARFARE_AGENT_HURT = registerSoundEvent("entity.kamenridercraft.god_warfare_agent.hurt");
	public static final Supplier<SoundEvent> GOD_WARFARE_AGENT_DEATH = registerSoundEvent("entity.kamenridercraft.god_warfare_agent.death");
	public static final Supplier<SoundEvent> GOD_WARFARE_AGENT_SHOOT = registerSoundEvent("entity.kamenridercraft.god_warfare_agent.shoot");
	public static final Supplier<SoundEvent> GOLEM_AMBIENT = registerSoundEvent("entity.kamenridercraft.golem.ambient");
	public static final Supplier<SoundEvent> GOLEM_HURT = registerSoundEvent("entity.kamenridercraft.golem.hurt");
	public static final Supplier<SoundEvent> GOLEM_DEATH = registerSoundEvent("entity.kamenridercraft.golem.death");
	public static final Supplier<SoundEvent> GOLEM_SHOOT = registerSoundEvent("entity.kamenridercraft.golem.shoot");
	public static final Supplier<SoundEvent> TOUTOGUARDIAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.touto_guardian.ambient");
	public static final Supplier<SoundEvent> TOUTOGUARDIAN_HURT = registerSoundEvent("entity.kamenridercraft.touto_guardian.hurt");
	public static final Supplier<SoundEvent> TOUTOGUARDIAN_DEATH = registerSoundEvent("entity.kamenridercraft.touto_guardian.death");
	public static final Supplier<SoundEvent> TOUTOGUARDIAN_SHOOT = registerSoundEvent("entity.kamenridercraft.touto_guardian.shoot");
	public static final Supplier<SoundEvent> HARD_GUARDIAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.hard_guardian.ambient");
	public static final Supplier<SoundEvent> HARD_GUARDIAN_HURT = registerSoundEvent("entity.kamenridercraft.hard_guardian.hurt");
	public static final Supplier<SoundEvent> HARD_GUARDIAN_DEATH = registerSoundEvent("entity.kamenridercraft.hard_guardian.death");
	public static final Supplier<SoundEvent> HARD_GUARDIAN_SHOOT = registerSoundEvent("entity.kamenridercraft.hard_guardian.shoot");
	public static final Supplier<SoundEvent> HOKUTOGUARDIAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.hokuto_guardian.ambient");
	public static final Supplier<SoundEvent> HOKUTOGUARDIAN_HURT = registerSoundEvent("entity.kamenridercraft.hokuto_guardian.hurt");
	public static final Supplier<SoundEvent> HOKUTOGUARDIAN_DEATH = registerSoundEvent("entity.kamenridercraft.hokuto_guardian.death");
	public static final Supplier<SoundEvent> HOKUTOGUARDIAN_SHOOT = registerSoundEvent("entity.kamenridercraft.hokuto_guardian.shoot");
	public static final Supplier<SoundEvent> KASSHINE_AMBIENT = registerSoundEvent("entity.kamenridercraft.kasshine.ambient");
	public static final Supplier<SoundEvent> KASSHINE_HURT = registerSoundEvent("entity.kamenridercraft.kasshine.hurt");
	public static final Supplier<SoundEvent> KASSHINE_DEATH = registerSoundEvent("entity.kamenridercraft.kasshine.death");
	public static final Supplier<SoundEvent> KASSHINE_SHOOT = registerSoundEvent("entity.kamenridercraft.kasshine.shoot");
	public static final Supplier<SoundEvent> KNIGHT_SOLDIER_AMBIENT = registerSoundEvent("entity.kamenridercraft.knight_soldier_mob.ambient");
	public static final Supplier<SoundEvent> KNIGHT_SOLDIER_HURT = registerSoundEvent("entity.kamenridercraft.knight_soldier_mob.hurt");
	public static final Supplier<SoundEvent> KNIGHT_SOLDIER_DEATH = registerSoundEvent("entity.kamenridercraft.knight_soldier_mob.death");
	public static final Supplier<SoundEvent> KNIGHT_SOLDIER_SHOOT = registerSoundEvent("entity.kamenridercraft.knight_soldier_mob.shoot");
	public static final Supplier<SoundEvent> KUROKAGE_TROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.kurokage_trooper.ambient");
	public static final Supplier<SoundEvent> KUROKAGE_TROOPER_HURT = registerSoundEvent("entity.kamenridercraft.kurokage_trooper.hurt");
	public static final Supplier<SoundEvent> KUROKAGE_TROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.kurokage_trooper.death");
	public static final Supplier<SoundEvent> KUROKAGE_TROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.kurokage_trooper.shoot");
	public static final Supplier<SoundEvent> MAGE_CAPTAIN_AMBIENT = registerSoundEvent("entity.kamenridercraft.mage_captain.ambient");
	public static final Supplier<SoundEvent> MAGE_CAPTAIN_HURT = registerSoundEvent("entity.kamenridercraft.mage_captain.hurt");
	public static final Supplier<SoundEvent> MAGE_CAPTAIN_DEATH = registerSoundEvent("entity.kamenridercraft.mage_captain.death");
	public static final Supplier<SoundEvent> MAGE_CAPTAIN_SHOOT = registerSoundEvent("entity.kamenridercraft.mage_captain.shoot");
	public static final Supplier<SoundEvent> MAGE_FOOTSOLDIER_AMBIENT = registerSoundEvent("entity.kamenridercraft.mage_footsoldier.ambient");
	public static final Supplier<SoundEvent> MAGE_FOOTSOLDIER_HURT = registerSoundEvent("entity.kamenridercraft.mage_footsoldier.hurt");
	public static final Supplier<SoundEvent> MAGE_FOOTSOLDIER_DEATH = registerSoundEvent("entity.kamenridercraft.mage_footsoldier.death");
	public static final Supplier<SoundEvent> MAGE_FOOTSOLDIER_SHOOT = registerSoundEvent("entity.kamenridercraft.mage_footsoldier.shoot");
	public static final Supplier<SoundEvent> MAKAMOU_NINJA_GROUP_AMBIENT = registerSoundEvent("entity.kamenridercraft.makamou_ninja_group.ambient");
	public static final Supplier<SoundEvent> MAKAMOU_NINJA_GROUP_HURT = registerSoundEvent("entity.kamenridercraft.makamou_ninja_group.hurt");
	public static final Supplier<SoundEvent> MAKAMOU_NINJA_GROUP_DEATH = registerSoundEvent("entity.kamenridercraft.makamou_ninja_group.death");
	public static final Supplier<SoundEvent> MAKAMOU_NINJA_GROUP_SHOOT = registerSoundEvent("entity.kamenridercraft.makamou_ninja_group.shoot");
	public static final Supplier<SoundEvent> MALGAM_AMBIENT = registerSoundEvent("entity.kamenridercraft.malgam.ambient");
	public static final Supplier<SoundEvent> MALGAM_HURT = registerSoundEvent("entity.kamenridercraft.malgam.hurt");
	public static final Supplier<SoundEvent> MALGAM_DEATH = registerSoundEvent("entity.kamenridercraft.malgam.death");
	public static final Supplier<SoundEvent> MALGAM_SHOOT = registerSoundEvent("entity.kamenridercraft.malgam.shoot");
	public static final Supplier<SoundEvent> MASQUERADE_AMBIENT = registerSoundEvent("entity.kamenridercraft.masquerade.ambient");
	public static final Supplier<SoundEvent> MASQUERADE_HURT = registerSoundEvent("entity.kamenridercraft.masquerade.hurt");
	public static final Supplier<SoundEvent> MASQUERADE_DEATH = registerSoundEvent("entity.kamenridercraft.masquerade.death");
	public static final Supplier<SoundEvent> MASQUERADE_SHOOT = registerSoundEvent("entity.kamenridercraft.masquerade.shoot");
	public static final Supplier<SoundEvent> NEBULA_BUGSTERVIRUS_AMBIENT = registerSoundEvent("entity.kamenridercraft.nebula_bugstervirus_mob.ambient");
	public static final Supplier<SoundEvent> NEBULA_BUGSTERVIRUS_HURT = registerSoundEvent("entity.kamenridercraft.nebula_bugstervirus_mob.hurt");
	public static final Supplier<SoundEvent> NEBULA_BUGSTERVIRUS_DEATH = registerSoundEvent("entity.kamenridercraft.nebula_bugstervirus_mob.death");
	public static final Supplier<SoundEvent> NEBULA_BUGSTERVIRUS_SHOOT = registerSoundEvent("entity.kamenridercraft.nebula_bugstervirus_mob.shoot");
	public static final Supplier<SoundEvent> NEOTROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.neotrooper.ambient");
	public static final Supplier<SoundEvent> NEOTROOPER_HURT = registerSoundEvent("entity.kamenridercraft.neotrooper.hurt");
	public static final Supplier<SoundEvent> NEOTROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.neotrooper.death");
	public static final Supplier<SoundEvent> NEOTROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.neotrooper.shoot");
	public static final Supplier<SoundEvent> NEW_MOLE_IMAGIN_SAND_AMBIENT = registerSoundEvent("entity.kamenridercraft.new_mole_imagin_sand.ambient");
	public static final Supplier<SoundEvent> NEW_MOLE_IMAGIN_SAND_HURT = registerSoundEvent("entity.kamenridercraft.new_mole_imagin_sand.hurt");
	public static final Supplier<SoundEvent> NEW_MOLE_IMAGIN_SAND_DEATH = registerSoundEvent("entity.kamenridercraft.new_mole_imagin_sand.death");
	public static final Supplier<SoundEvent> NEW_MOLE_IMAGIN_SAND_SHOOT = registerSoundEvent("entity.kamenridercraft.new_mole_imagin_sand.shoot");
	public static final Supplier<SoundEvent> PANTHERAS_LUTEUS_AMBIENT = registerSoundEvent("entity.kamenridercraft.pantheras_luteus.ambient");
	public static final Supplier<SoundEvent> PANTHERAS_LUTEUS_HURT = registerSoundEvent("entity.kamenridercraft.pantheras_luteus.hurt");
	public static final Supplier<SoundEvent> PANTHERAS_LUTEUS_DEATH = registerSoundEvent("entity.kamenridercraft.pantheras_luteus.death");
	public static final Supplier<SoundEvent> PANTHERAS_LUTEUS_SHOOT = registerSoundEvent("entity.kamenridercraft.pantheras_luteus.shoot");
	public static final Supplier<SoundEvent> PAWN_JYAMATO_AMBIENT = registerSoundEvent("entity.kamenridercraft.pawnjyamato_mob.ambient");
	public static final Supplier<SoundEvent> PAWN_JYAMATO_HURT = registerSoundEvent("entity.kamenridercraft.pawnjyamato_mob.hurt");
	public static final Supplier<SoundEvent> PAWN_JYAMATO_DEATH = registerSoundEvent("entity.kamenridercraft.pawnjyamato_mob.death");
	public static final Supplier<SoundEvent> PAWN_JYAMATO_SHOOT = registerSoundEvent("entity.kamenridercraft.pawnjyamato_mob.shoot");
	public static final Supplier<SoundEvent> REAPER_LEGION_AMBIENT = registerSoundEvent("entity.kamenridercraft.reaper_legion.ambient");
	public static final Supplier<SoundEvent> REAPER_LEGION_HURT = registerSoundEvent("entity.kamenridercraft.reaper_legion.hurt");
	public static final Supplier<SoundEvent> REAPER_LEGION_DEATH = registerSoundEvent("entity.kamenridercraft.reaper_legion.death");
	public static final Supplier<SoundEvent> REAPER_LEGION_SHOOT = registerSoundEvent("entity.kamenridercraft.reaper_legion.shoot");
	public static final Supplier<SoundEvent> RED_FOLLWER_AMBIENT = registerSoundEvent("entity.kamenridercraft.red_follower.ambient");
	public static final Supplier<SoundEvent> RED_FOLLWER_HURT = registerSoundEvent("entity.kamenridercraft.red_follower.hurt");
	public static final Supplier<SoundEvent> RED_FOLLWER_DEATH = registerSoundEvent("entity.kamenridercraft.red_follower.death");
	public static final Supplier<SoundEvent> RED_FOLLWER_SHOOT = registerSoundEvent("entity.kamenridercraft.red_follower.shoot");
	public static final Supplier<SoundEvent> RIDEPLAYER_AMBIENT = registerSoundEvent("entity.kamenridercraft.rideplayer.ambient");
	public static final Supplier<SoundEvent> RIDEPLAYER_HURT = registerSoundEvent("entity.kamenridercraft.rideplayer.hurt");
	public static final Supplier<SoundEvent> RIDEPLAYER_DEATH = registerSoundEvent("entity.kamenridercraft.rideplayer.death");
	public static final Supplier<SoundEvent> RIDEPLAYER_SHOOT = registerSoundEvent("entity.kamenridercraft.rideplayer.shoot");
	public static final Supplier<SoundEvent> RIOTROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.riotrooper.ambient");
	public static final Supplier<SoundEvent> RIOTROOPER_HURT = registerSoundEvent("entity.kamenridercraft.riotrooper.hurt");
	public static final Supplier<SoundEvent> RIOTROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.riotrooper.death");
	public static final Supplier<SoundEvent> RIOTROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.riotrooper.shoot");
	public static final Supplier<SoundEvent> ROIDMUDE_AMBIENT = registerSoundEvent("entity.kamenridercraft.roidmude.ambient");
	public static final Supplier<SoundEvent> ROIDMUDE_HURT = registerSoundEvent("entity.kamenridercraft.roidmude.hurt");
	public static final Supplier<SoundEvent> ROIDMUDE_DEATH = registerSoundEvent("entity.kamenridercraft.roidmude.death");
	public static final Supplier<SoundEvent> ROIDMUDE_SHOOT = registerSoundEvent("entity.kamenridercraft.roidmude.shoot");
	public static final Supplier<SoundEvent> SEITOGUARDIAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.seito_guardian.ambient");
	public static final Supplier<SoundEvent> SEITOGUARDIAN_HURT = registerSoundEvent("entity.kamenridercraft.seito_guardian.hurt");
	public static final Supplier<SoundEvent> SEITOGUARDIAN_DEATH = registerSoundEvent("entity.kamenridercraft.seito_guardian.death");
	public static final Supplier<SoundEvent> SEITOGUARDIAN_SHOOT = registerSoundEvent("entity.kamenridercraft.seito_guardian.shoot");
	public static final Supplier<SoundEvent> SHADOW_TROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.shadow_trooper.ambient");
	public static final Supplier<SoundEvent> SHADOW_TROOPER_HURT = registerSoundEvent("entity.kamenridercraft.shadow_trooper.hurt");
	public static final Supplier<SoundEvent> SHADOW_TROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.shadow_trooper.death");
	public static final Supplier<SoundEvent> SHADOW_TROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.shadow_trooper.shoot");
	public static final Supplier<SoundEvent> SHIMI_AMBIENT = registerSoundEvent("entity.kamenridercraft.shimi.ambient");
	public static final Supplier<SoundEvent> SHIMI_HURT = registerSoundEvent("entity.kamenridercraft.shimi.hurt");
	public static final Supplier<SoundEvent> SHIMI_DEATH = registerSoundEvent("entity.kamenridercraft.shimi.death");
	public static final Supplier<SoundEvent> SHIMI_SHOOT = registerSoundEvent("entity.kamenridercraft.shimi.shoot");
	public static final Supplier<SoundEvent> SHOCKER_COMBATMAN_AMBIENT = registerSoundEvent("entity.kamenridercraft.shocker_combatman.ambient");
	public static final Supplier<SoundEvent> SHOCKER_COMBATMAN_HURT = registerSoundEvent("entity.kamenridercraft.shocker_combatman.hurt");
	public static final Supplier<SoundEvent> SHOCKER_COMBATMAN_DEATH = registerSoundEvent("entity.kamenridercraft.shocker_combatman.death");
	public static final Supplier<SoundEvent> SHOCKER_COMBATMAN_SHOOT = registerSoundEvent("entity.kamenridercraft.shocker_combatman.shoot");
	public static final Supplier<SoundEvent> SMASH_AMBIENT = registerSoundEvent("entity.kamenridercraft.needle_smash.ambient");
	public static final Supplier<SoundEvent> SMASH_HURT = registerSoundEvent("entity.kamenridercraft.needle_smash.hurt");
	public static final Supplier<SoundEvent> SMASH_DEATH = registerSoundEvent("entity.kamenridercraft.needle_smash.death");
	public static final Supplier<SoundEvent> SMASH_SHOOT = registerSoundEvent("entity.kamenridercraft.needle_smash.shoot");
	public static final Supplier<SoundEvent> TRILOBITE_MAGIA_AMBIENT = registerSoundEvent("entity.kamenridercraft.trilobite_magia.ambient");
	public static final Supplier<SoundEvent> TRILOBITE_MAGIA_HURT = registerSoundEvent("entity.kamenridercraft.trilobite_magia.hurt");
	public static final Supplier<SoundEvent> TRILOBITE_MAGIA_DEATH = registerSoundEvent("entity.kamenridercraft.trilobite_magia.death");
	public static final Supplier<SoundEvent> TRILOBITE_MAGIA_SHOOT = registerSoundEvent("entity.kamenridercraft.trilobite_magia.shoot");
	public static final Supplier<SoundEvent> YUMMY_AMBIENT = registerSoundEvent("entity.kamenridercraft.yummy_mob.ambient");
	public static final Supplier<SoundEvent> YUMMY_HURT = registerSoundEvent("entity.kamenridercraft.yummy_mob.hurt");
	public static final Supplier<SoundEvent> YUMMY_DEATH = registerSoundEvent("entity.kamenridercraft.yummy_mob.death");
	public static final Supplier<SoundEvent> YUMMY_SHOOT = registerSoundEvent("entity.kamenridercraft.yummy_mob.shoot");
	public static final Supplier<SoundEvent> ZECTROOPER_AMBIENT = registerSoundEvent("entity.kamenridercraft.zectrooper.ambient");
	public static final Supplier<SoundEvent> ZECTROOPER_HURT = registerSoundEvent("entity.kamenridercraft.zectrooper.hurt");
	public static final Supplier<SoundEvent> ZECTROOPER_DEATH = registerSoundEvent("entity.kamenridercraft.zectrooper.death");
	public static final Supplier<SoundEvent> ZECTROOPER_SHOOT = registerSoundEvent("entity.kamenridercraft.zectrooper.shoot");
	public static final Supplier<SoundEvent> ZEIN_ENEMY_SUMMON_AMBIENT = registerSoundEvent("entity.kamenridercraft.zein_enemy_summon.ambient");
	public static final Supplier<SoundEvent> ZEIN_ENEMY_SUMMON_HURT = registerSoundEvent("entity.kamenridercraft.zein_enemy_summon.hurt");
	public static final Supplier<SoundEvent> ZEIN_ENEMY_SUMMON_DEATH = registerSoundEvent("entity.kamenridercraft.zein_enemy_summon.death");
	public static final Supplier<SoundEvent> ZEIN_ENEMY_SUMMON_SHOOT = registerSoundEvent("entity.kamenridercraft.zein_enemy_summon.shoot");
	public static final Supplier<SoundEvent> ZU_GUMUN_BA_AMBIENT = registerSoundEvent("entity.kamenridercraft.zu_gumun_ba.ambient");
	public static final Supplier<SoundEvent> ZU_GUMUN_BA_HURT = registerSoundEvent("entity.kamenridercraft.zu_gumun_ba.hurt");
	public static final Supplier<SoundEvent> ZU_GUMUN_BA_DEATH = registerSoundEvent("entity.kamenridercraft.zu_gumun_ba.death");
	public static final Supplier<SoundEvent> ZU_GUMUN_BA_SHOOT = registerSoundEvent("entity.kamenridercraft.zu_gumun_ba.shoot");

	private static Supplier<SoundEvent> registerSoundEvent(String name) {
		ResourceLocation id = ResourceLocation.fromNamespaceAndPath(KamenRiderCraftSoundEvents.MODID, name);
		return SOUND_EVENTS.register(name, () -> SoundEvent.createVariableRangeEvent(id));
	}

	public static void register(IEventBus eventBus) {
		SOUND_EVENTS.register(eventBus);
	}

	public KamenRiderCraftSoundEvents(IEventBus modEventBus, ModContainer modContainer) {
		register(modEventBus);
	}
}
